Update Linux check_mk agent and plugins to 1.4.0p8.

diff --git a/roles/install-cmkagent/templates/check_mk_agent.linux.j2 b/roles/install-cmkagent/templates/check_mk_agent.linux.j2
--- a/roles/install-cmkagent/templates/check_mk_agent.linux.j2
+++ b/roles/install-cmkagent/templates/check_mk_agent.linux.j2
@@ -244,7 +244,7 @@ function run_real_time_checks()
 }
 
 echo '<<<check_mk>>>'
-echo Version: 1.4.0p5
+echo Version: 1.4.0p8
 echo AgentOS: linux
 echo Hostname: $HOSTNAME
 echo AgentDirectory: $MK_CONFDIR
@@ -300,15 +300,15 @@ then
     sed -n '/ nfs4\? /s/[^ ]* \([^ ]*\) .*/\1/p' < /proc/mounts |
         sed 's/\\040/ /g' |
         while read MP
-	do
-	 if [ $STAT_VERSION != $STAT_BROKE ]; then
-	    waitmax -s 9 2 stat -f -c "$MP ok %b %f %a %s" "$MP" || \
-		echo "$MP hanging 0 0 0 0"
-	 else
-	    waitmax -s 9 2 stat -f -c "$MP ok %b %f %a %s" "$MP" && \
-	    printf '\n'|| echo "$MP hanging 0 0 0 0"
-	 fi
-	done
+        do
+         if [ $STAT_VERSION != $STAT_BROKE ]; then
+            waitmax -s 9 2 stat -f -c "$MP ok %b %f %a %s" "$MP" || \
+                echo "$MP hanging 0 0 0 0"
+         else
+            waitmax -s 9 2 stat -f -c "$MP ok %b %f %a %s" "$MP" && \
+            printf '\n'|| echo "$MP hanging 0 0 0 0"
+         fi
+        done
 
     echo '<<<cifsmounts>>>'
     sed -n '/ cifs\? /s/[^ ]* \([^ ]*\) .*/\1/p' < /proc/mounts |
@@ -576,7 +576,10 @@ fi
 
 # Status of CUPS printer queues
 if type lpstat > /dev/null 2>&1; then
-    if pgrep -f "\bcupsd" > /dev/null 2>&1; then
+    # Systemd starts cupsd on demand: Instead of checking that the cupsd is
+    # running we check that the cups service exists and is enabled.
+    if pgrep -f "\bcupsd" > /dev/null 2>&1 \
+       || (type systemctl >/dev/null 2>&1 && systemctl is-enabled cups.service); then
         # first define a function to check cups
         function cups_queues () {
             CPRINTCONF=/etc/cups/printers.conf
@@ -725,22 +728,24 @@ then
     run_cached -s omd_status 60 "omd status --bare --auto || true"
     echo '<<<mknotifyd:sep(0)>>>'
     for statefile in /omd/sites/*/var/log/mknotifyd.state ; do
-	if [ -e "$statefile" ] ; then
-	    site=${statefile%/var/log*}
-	    site=${site#/omd/sites/}
-	    echo "[$site]"
-	    grep -v '^#' < $statefile
+    if [ -e "$statefile" ] ; then
+        site=${statefile%/var/log*}
+        site=${site#/omd/sites/}
+        echo "[$site]"
+        grep -v '^#' < $statefile
         fi
     done
 
     echo '<<<omd_apache:sep(124)>>>'
     for statsfile in /omd/sites/*/var/log/apache/stats; do
-	if [ -e "$statsfile" ] ; then
-	    site=${statsfile%/var/log*}
-	    site=${site#/omd/sites/}
-	    echo "[$site]"
+    if [ -e "$statsfile" ] ; then
+        site=${statsfile%/var/log*}
+        site=${site#/omd/sites/}
+        echo "[$site]"
             cat $statsfile
             > $statsfile
+            # prevent next section to fail caused by a missing newline at the end of the statsfile
+            echo
         fi
     done
 fi
